/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-121253-g8a34faa250-20250927"
#endif /* AVUTIL_FFVERSION_H */
